FinalProject/Models/Deck.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.Models
{
    public class Deck
    {
        public int Id { get; set; }
        public int UserInventoryId { get; set; }
        public UserInventory UserInventory { get; set; }
        public string DeckName { get; set; }
        public string BuildPurpose { get; set; }
        public string DeckImage { get; set; }
        public List<DeckCardMapping> DeckCardMappings { get; set; }
        public byte[] ImageBytes { get; set; }
    }
}

FinalProject/Controllers/DeckController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FinalProject.Data.Interfaces;
using FinalProject.Models;
using FinalProject.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class DeckController : Controller
    {
        private IDataAccess _DataAccess;
        public DeckController(IDataAccess dataAccess)
        {
            _DataAccess = dataAccess;

        }
        // GET: DeckController
        public async Task<ActionResult> Index()
        {
            var defaultImage = await _DataAccess.DefaultImageDataAccess.GetDefaultImageByIdBytesAync(1);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            if (string.IsNullOrWhiteSpace(userId))
            {
                return RedirectToAction("Home", "Index");
            }
            else
            {
                var userInventory = await _DataAccess.UserInventoryDataAccess.GetUserInventoryByUserAsync(userId);
                var decks = await _DataAccess.DeckDataAccess.GetDecksByUserAsync(userInventory.Id);
                var cards = await _DataAccess.CardDataAccess.GetCardMappingsForUserAsync(userInventory.Id);
                var model = new DeckIndexViewModel();
                model.Decks = decks;
                model.DefaultImageBytes = defaultImage;
                model.CardMappings = cards;
                return View(model);
            }
        }
        public async Task<IActionResult> CardDetails(string cardId, string deckId)
        {
            var model = new DeckCardDetailsViewModel();
            int convertedCardId;
            int convertedDeckId;  
            if (int.TryParse(cardId, out convertedCardId) && int.TryParse(deckId, out convertedDeckId))
            {
                var card = await _DataAccess.CardDataAccess.GetCardAsync(convertedCardId);
                model.Card = card;
                model.DeckId = deckId;
                return View("CardDetails", model);
            }
            else
            {
                var detailsModel = new DeckDetailsViewModel();
                detailsModel.DeckId = deckId;
                return RedirectToAction("Edit", detailsModel);
            }
           
        }
        public ActionResult RedirectToDeck(string deckId)
        {
            var model = new DeckDetailsViewModel();
            model.DeckId = deckId;
            return RedirectToAction("Edit", model);

        }
        // GET: DeckController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var defaultImage = await _DataAccess.DefaultImageDataAccess.GetDefaultImageByIdBytesAync(1);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            if (string.IsNullOrWhiteSpace(userId))
            {
                return RedirectToAction("Home", "Index");
            }
            else
            {
                var model = new DeckDetailsViewModel();
                model.DefaultImageBytes = defaultImage;
                model.Deck = await _DataAccess.DeckDataAccess.GetDeckAsync(id);
                if (model.Deck == null)
                {
                    model = null;
                }
                var userInventory = await _DataAccess.UserInventoryDataAccess.GetUserInventoryByUserAsync(userId);
                var cards = await _DataAccess.CardDataAccess.GetCardMappingsForUserAsync(userInventory.Id);
                if (model == null)
                {
                    model = new DeckDetailsViewModel();
                    var deck = new Deck();
                    deck.UserInventoryId = userInventory.Id;
                    deck = await _DataAccess.DeckDataAccess.Upsert(deck);
                    model.Deck = deck;
                }
                model.CardMappings = cards;
                return View(model);
            }
        }

        // GET: DeckController/Edit
        public async Task<ActionResult> Edit(DeckDetailsViewModel model)
        {
            
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            if (string.IsNullOrWhiteSpace(userId))
            {
                return RedirectToAction("Home", "Index");
            }
            else
            {
                if (model != null)
                {
                    int deckId;
                    if (int.TryParse(model.DeckId, out deckId))
                    {
                        model.Deck = await _DataAccess.DeckDataAccess.GetDeckAsync(deckId);
                        if (model.Deck == null)
                        {
                            model = null;
                        }
                    }
                    else
                    {
                            model = null;
                    }   
                }
                var userInventory = await _DataAccess.UserInventoryDataAccess.GetUserInventoryByUserAsync(userId);
                var cards = await _DataAccess.CardDataAccess.GetCardMappingsForUserAsync(userInventory.Id);
                if (model == null)
                {
                    model = new DeckDetailsViewModel();
                    var deck = new Deck();
                    deck.UserInventoryId = userInventory.Id;
                    deck = await _DataAccess.DeckDataAccess.Upsert(deck);
                    model.Deck = deck;
                }
                model.CardMappings = cards;
                return View(model);
            }
        }
        // POST: DeckController/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormCollection collection)
        {
            try
            {
                var deckName = collection["Deck.DeckName"];
                var buildPrupose = collection["Deck.BuildPurpose"];
                var stringdeckId = collection["Deck.Id"];
                int deckId;
                if (int.TryParse(stringdeckId, out deckId))
                {
                    var deck = await _DataAccess.DeckDataAccess.GetDeckAsync(deckId);
                    deck.DeckName = deckName;
                    deck.BuildPurpose = buildPrupose;
                    await _DataAccess.DeckDataAccess.Upsert(deck);
                    var model = new DeckDetailsViewModel();
                    model.DeckId = stringdeckId;

                    return RedirectToAction("Edit", model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        // POST: DeckController/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateImage(IFormCollection collection)
        {
            try
            {
                var file = collection.Files.FirstOrDefault();
                if(file != null)
                {
                    var stringdeckId = collection["Deck.Id"];
                    if (!string.IsNullOrEmpty(stringdeckId))
                    {
                        int deckId;
                        if(int.TryParse(stringdeckId, out deckId))
                        {
                            using (var ms = new MemoryStream())
                            {
                                file.CopyTo(ms);
                                var fileBytes = ms.ToArray();
                                var deck = await _DataAccess.DeckDataAccess.GetDeckAsync(deckId);
                                if(deck != null)
                                {
                                    deck.ImageBytes = fileBytes;
                                    await _DataAccess.DeckDataAccess.Upsert(deck);
                                }

                            }
                        }
                    }
                    
                }
                var model = new DeckDetailsViewModel();
                model.DeckId = collection["Deck.Id"];
                return RedirectToAction("Edit", model);
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public async Task<IActionResult> AddCard(DeckDetailsViewModel model)
        {
            int cardId;
            int deckId;
            if (int.TryParse(model.CardIdToAdd, out cardId) && int.TryParse(model.DeckId, out deckId))
            {
                var mapping = await _DataAccess.DeckDataAccess.GetDeckCardMappingAsync(deckId, cardId);
                if (mapping != null)
                {
                    mapping.Count++;
                    await _DataAccess.DeckDataAccess.UpsertDeckCardMappingAsync(mapping);
                }
                else
                {
                    mapping = new DeckCardMapping();
                    mapping.CardId = cardId;
                    mapping.DeckId = deckId;
                    mapping.Count = 1;
                    await _DataAccess.DeckDataAccess.UpsertDeckCardMappingAsync(mapping);

                }
            }
            return RedirectToAction("Edit", model);
        }
        public async Task<IActionResult> IncreaseCardCount(string dId, string cId)
        {
            int cardId;
            int deckId;
            if (int.TryParse(cId, out cardId) && int.TryParse(dId, out deckId))
            {
                var mapping = await _DataAccess.DeckDataAccess.GetDeckCardMappingAsync(deckId, cardId);
                if (mapping != null)
                {
                    mapping.Count++;
                    await _DataAccess.DeckDataAccess.UpsertDeckCardMappingAsync(mapping);
                }
                else
                {
                    mapping = new DeckCardMapping();

FinalProject/Views/Deck/CardDetails.cshtml
@model FinalProject.Models.ViewModels.DeckCardDetailsViewModel

@{
    ViewData["Title"] = "Card Details";
}

<h1>Card Details</h1>

<div class="container">
    <div class="row">
        <div class="col">
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.Name)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.Name)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.Type)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.Type)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.Description)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.Description)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.Attack)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.Attack)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.Defence)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.Defence)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.Level)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.Level)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.Race)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.Race)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.Attribute)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.Attribute)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.Archetype)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.Archetype)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.Linkval)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.Linkval)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Card.LinkMarkers)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Card.LinkMarkers)
                </dd>
            </dl>
        </div>
        <div class="col">
            @{
                string imgSrc;
                if (Model.Card.ImageBytes != null)
                {
                    var base64 = Convert.ToBase64String(Model.Card.ImageBytes);
                    imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                }
                else
                {
                    imgSrc = "https://static.giantbomb.com/uploads/original/9/95666/1878961-pik.gif";
                }
            }
            <img style="height: 578px; width: 400px;" src="@imgSrc" />
        </div>
    </div>
</div>
<div>
    <a asp-action="RedirectToDeck" asp-route-deckid="@Model.DeckId">Back to Deck</a>
</div>

FinalProject/Views/Deck/Create.cshtml
@model FinalProject.Models.ViewModels.DeckDetailsViewModel

@{
    ViewData["Title"] = "Create";
}
<h4>Deck Builder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Deck.DeckName" class="control-label"></label>
                <input asp-for="Deck.DeckName" class="form-control" />
                <span asp-validation-for="Deck.DeckName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<h4>Deck Cards</h4>
<hr />
<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Type
                </th>
                <th>
                    Attack
                </th>
                <th>
                    Defense
                </th>
                <th>
                    Level
                </th>
                <th>
                    Race
                </th>
                <th>
                    Attribute
                </th>
                <th>
                    Archetype
                </th>
                <th>
                    Linkval
                </th>
                <th>
                    LinkMarkers
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Deck.DeckCardMappings)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.AttackDisplay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.DefenseDisplay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.LevelDisplay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.Race)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.Attribute)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.Archetype)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.LinkvalDisplay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.LinkMarkers)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Card.Id">Details</a>
                    </td>
                    <td>
                        <a asp-action="RemoveCard" asp-route-deckid="@Model.Deck.Id" asp-route-cardid="@item.Card.Id">-</a>
                        @Html.DisplayFor(modelItem => item.Count)
                        <a asp-action="AddCard" asp-route-deckid="@Model.Deck.Id" asp-route-cardid="@item.Card.Id">+</a>
                    </td>
                </tr>
            }
            <tr>
                <td>
                    <button id="btnShowModal" type="button"
                            class="btn btn-primary">
                        Add Card
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Index">Back</a>
</div>
<div class="modal fade" tabindex="-1" id="loginModal"
     data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Card From Collection</h4>
                </div>
                <form asp-action="AddCard" asp-controller="Deck" method="post">
                    <div class="modal-body">
                        <input asp-for="@Model.DeckId" type ="hidden" value="@Model.Deck.Id"/>

                        <select asp-for="@Model.CardIdToAdd" asp-items="Model.Cards"></select>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-primary" value="Add" />
                        <button type="button" id="btnHideModal" class="btn btn-secondary">
                            Cancel
                        </button>
                    </div>
                </form>

            </div>
        </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">

</script>
<script src="bootstrap/js/bootstrap.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
        $("#btnShowModal").click(function () {
            $("#loginModal").modal('show');
        });

        $("#btnHideModal").click(function () {
            $("#loginModal").modal('hide');
        });
    });
</script>

FinalProject/Views/Deck/Details.cshtml
@model FinalProject.Models.ViewModels.DeckDetailsViewModel

@{
    ViewData["Title"] = "Edit Deck";
}
<h4>Deck Builder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <div>
            <p>
                <h4>
                    @Html.DisplayNameFor(model => model.Deck.DeckName)
                </h4>
                @Html.DisplayFor(model => model.Deck.DeckName)
            </p>
            <p>
                <h4>
                    @Html.DisplayNameFor(model => model.Deck.BuildPurpose)
                </h4>
                @Html.DisplayFor(model => model.Deck.BuildPurpose)
            </p>
        </div>
    </div>
    <div class="col-md-4">
        @{

            string imgSrc;
            if (Model.Deck.ImageBytes != null)
            {
                var base64 = Convert.ToBase64String(Model.Deck.ImageBytes);
                imgSrc = String.Format("data:image/gif;base64,{0}", base64);
            }
            else
            {
                if (Model.DefaultImageBytes != null)
                {
                    var base64 = Convert.ToBase64String(Model.DefaultImageBytes);
                    imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                }
                else
                {
                    imgSrc = "";
                }
                imgSrc = "https://static.giantbomb.com/uploads/original/9/95666/1878961-pik.gif";
            }

        }
    </div>
</div>
<h4>Deck Cards</h4>
<hr />
<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Type
                </th>
                <th>
                    Attack
                </th>
                <th>
                    Defense
                </th>
                <th>
                    Level
                </th>
                <th>
                    Race
                </th>
                <th>
                    Attribute
                </th>
                <th>
                    Archetype
                </th>
                <th>
                    Linkval
                </th>
                <th>
                    LinkMarkers
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Deck.DeckCardMappings)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Card.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Card.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Card.AttackDisplay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Card.DefenseDisplay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Card.LevelDisplay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Card.Race)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Card.Attribute)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Card.Archetype)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Card.LinkvalDisplay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Card.LinkMarkers)
                </td>
                <td>
                    <a asp-action="CardDetails" asp-route-cardid="@item.Card.Id" asp-route-deckid="@Model.Deck.Id">Details</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Count)
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Edit" asp-route-deckid="@Model.Deck.Id">Edit</a>
    <a asp-action="Delete" asp-route-id="@Model.Deck.Id">Delete</a>
    <a asp-action="Index">Back</a>
</div>

FinalProject/Views/Deck/Edit.cshtml
@model FinalProject.Models.ViewModels.DeckDetailsViewModel

@{
    ViewData["Title"] = "Edit Deck";
}
<h4>Deck Builder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Deck.DeckName" class="control-label"></label>
                <input asp-for="Deck.DeckName" class="form-control" />
                <span asp-validation-for="Deck.BuildPurpose" class="text-danger"></span>
                <label asp-for="Deck.BuildPurpose" class="control-label"></label>
                <input asp-for="Deck.BuildPurpose" class="form-control" />
                <span asp-validation-for="Deck.BuildPurpose" class="text-danger"></span>
                <input asp-for="Deck.Id" type="hidden" value="@Model.Deck.Id" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save Changes" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        @{ 

            string imgSrc;
            if (Model.Deck.ImageBytes != null)
            {
                var base64 = Convert.ToBase64String(Model.Deck.ImageBytes);
                imgSrc = String.Format("data:image/gif;base64,{0}", base64);
            }
            else
            {
                if (Model.DefaultImageBytes != null)
                {
                    var base64 = Convert.ToBase64String(Model.DefaultImageBytes);
                    imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                }
                imgSrc = "";
            }
        }
        @using (Html.BeginForm("UpdateImage", "Deck", FormMethod.Post,
                          new { enctype = "multipart/form-data" }))
        {
            <label for="file">Upload Image:</label>
            <input type="file" name="file" id="file" style="width: 100%;" />
            <input asp-for="Deck.Id" type="hidden" value="@Model.Deck.Id" />
            <input type="submit" value="Upload" class="submit" />
        }
    </div>
</div>
<h4>Deck Cards</h4>
<hr />
<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Type
                </th>
                <th>
                    Attack
                </th>
                <th>
                    Defense
                </th>
                <th>
                    Level
                </th>
                <th>
                    Race
                </th>
                <th>
                    Attribute
                </th>
                <th>
                    Archetype
                </th>
                <th>
                    Linkval
                </th>
                <th>
                    LinkMarkers
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Deck.DeckCardMappings)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.AttackDisplay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.DefenseDisplay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.LevelDisplay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.Race)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.Attribute)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.Archetype)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.LinkvalDisplay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Card.LinkMarkers)
                    </td>
                    <td>
                        <a asp-action="CardDetails" asp-route-cardid="@item.Card.Id" asp-route-deckid="@Model.Deck.Id">Details</a>
                    </td>   
                    <td>
                        <a asp-action="DecreaseCardCount" asp-route-dId="@Model.Deck.Id" asp-route-cId="@item.Card.Id">-</a>
                        @Html.DisplayFor(modelItem => item.Count)
                        <a asp-action="IncreaseCardCount" asp-route-dId="@Model.Deck.Id" asp-route-cId="@item.Card.Id">+</a>
                    </td>
                </tr>
            }
            <tr>
                <td>
                    <button id="btnShowModal" type="button"
                            class="btn btn-primary">
                        Add Card
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Index">Back</a>
</div>
<div class="modal fade" tabindex="-1" id="loginModal"
     data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Card From Collection</h4>
                </div>
                <form asp-action="AddCard" asp-controller="Deck" method="post">
                    <div class="modal-body">
                        <input asp-for="@Model.DeckId" type ="hidden" value="@Model.Deck.Id"/>

                        <select asp-for="@Model.CardIdToAdd" asp-items="Model.Cards"></select>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-primary" value="Add" />
                        <button type="button" id="btnHideModal" class="btn btn-secondary">
                            Cancel
                        </button>
                    </div>
                </form>

            </div>
        </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">

</script>
<script src="bootstrap/js/bootstrap.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
        $("#btnShowModal").click(function () {
            $("#loginModal").modal('show');
        });

        $("#btnHideModal").click(function () {
            $("#loginModal").modal('hide');
        });
    });
</script>