FinalProject/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FinalProject.Data.Interfaces;
using FinalProject.Models;
using FinalProject.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class DashboardController : Controller
    {
        private IDataAccess _DataAccess;
        public DashboardController(IDataAccess dataAccess)
        {
            _DataAccess = dataAccess;
        }
        public async Task<IActionResult> Index()
        {
            var defaultImage = await _DataAccess.DefaultImageDataAccess.GetDefaultImageByIdBytesAync(1);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            var tradeListings = await _DataAccess.TradeDataAccess.GetTradeListingsByUser(userId);
            var rating = await _DataAccess.TradeDataAccess.GetUserRating(userId);
            var userName = User.FindFirstValue(ClaimTypes.Name);
            var userInventory = await _DataAccess.UserInventoryDataAccess.GetUserInventoryByUserAsync(userId); 
            if(userInventory == null)
            {
                userInventory = new UserInventory();
                userInventory.ApplicationUserId = userId;
                userInventory = await _DataAccess.UserInventoryDataAccess.Upsert(userInventory);
            }
            var model = new DashboardIndexViewModel();
            model.Name = userName;
            model.UserInventory = userInventory;
            model.CardMappings = await _DataAccess.CardDataAccess.GetCardMappingsForUserAsync(userInventory.Id);
            model.Decks = await _DataAccess.DeckDataAccess.GetDecksByUserAsync(userInventory.Id);
            model.DefaultImageBytes = defaultImage;
            model.TradeListings = tradeListings;
            model.Rating = rating;
            model.TradeOffers = await _DataAccess.TradeDataAccess.GetTradeOffersByUserAync(userId);
            model.Friends = await _DataAccess.UserInventoryDataAccess.GetFriends(userInventory.Id);
            model.BlockList = await _DataAccess.UserInventoryDataAccess.GetBlocks(userInventory.Id);
            return View(model);
        }
    }
}

FinalProject/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FinalProject.Data;
using FinalProject.Data.Interfaces;
using FinalProject.Models;
using FinalProject.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;


namespace FinalProject.Controllers
{
    public class SearchController : Controller
    {
        private IYGOProDeckAccess _YGOProDeckAccess;
        private IDataAccess _DataAccess;
        

        public SearchController(IYGOProDeckAccess yGOProDeckAccess, IDataAccess dataAccess)
        {
            _YGOProDeckAccess = yGOProDeckAccess;
            _DataAccess = dataAccess;
        }
        public async Task<IActionResult> Index(string Query)
        {
            var model = new SearchIndexViewModel();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!string.IsNullOrWhiteSpace(userId))
            {
                var userInventory = await _DataAccess.UserInventoryDataAccess.GetUserInventoryByUserAsync(userId);
                var decks = await _DataAccess.DeckDataAccess.GetDecksByUserAsync(userInventory.Id);
                model.Decks = decks;

            }
            if (!string.IsNullOrWhiteSpace(Query))
            {
                model.Query = Query;
                model.Results = await _YGOProDeckAccess.SearchCardsAsync(Query);

            }
            else
            {
                model.Query = string.Empty;
                model.Results = new List<Card>();

            }
            return View(model);
        }
        public async Task<IActionResult> Details(string Name, string query)
        {
            var model = new SearchDetailsViewModel();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!string.IsNullOrWhiteSpace(userId))
            {
                var userInventory = await _DataAccess.UserInventoryDataAccess.GetUserInventoryByUserAsync(userId);
                var decks = await _DataAccess.DeckDataAccess.GetDecksByUserAsync(userInventory.Id);
                model.Decks = decks;

            }
            model.Query = query;
            if (!string.IsNullOrWhiteSpace(Name))
            {
                model.Name = Name;
                model.Result = await _YGOProDeckAccess.GetCardByNameAsync(Name);
                var card = await _DataAccess.CardDataAccess.GetCardByNameAsync(Name);
                if(card != null)
                {
                    model.Result = card;
                    var listings = await _DataAccess.TradeDataAccess.GetTradeListingsByCard(card.Id);
                    if(listings != null)
                    {
                        var filteredListings = listings.Where(x => TradeDataAccess.IsStateDeletable(x.TradeState)).ToList();
                        model.Listings = filteredListings;
                    }
                }
            }
            else
            {
                return View("Index");
            }
            if (string.IsNullOrWhiteSpace(model.Result?.Name))
            {

                return View("Index");
            }
            return View(model);
        }
        public async Task<IActionResult> AddCard(string name, string query)
        {
            var model = new SearchDetailsViewModel();
            model.Query = query;
            model.Name = name;      
            var cardData = await _DataAccess.CardDataAccess.GetCardByNameAsync(name);
            if(cardData == null)
            {
                var apiCard = await _YGOProDeckAccess.GetCardByNameAsync(name);
                if(apiCard.CardImages != null && apiCard.CardImages.Count > 0)
                {
                    apiCard.ImageBytes = _YGOProDeckAccess.GetCardImage(apiCard.CardImages.First());
                }
                cardData = await _DataAccess.CardDataAccess.Upsert(apiCard);        
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            if (string.IsNullOrWhiteSpace(userId))
            {
                return RedirectToAction("Home","Index" );
            }
            var userInventory = await _DataAccess.UserInventoryDataAccess.GetUserInventoryByUserAsync(userId);
            var cardmapping = await _DataAccess.CardDataAccess.GetSpecificCardMappingForUserAsync(userInventory.Id, cardData.Id);
            if (cardmapping != null)
            {
                cardmapping.Count++;
                await _DataAccess.CardDataAccess.UpsertCardMappingAsync(cardmapping);
            }
            else
            {
                cardmapping = new InventoryCardMapping();
                cardmapping.CardId = cardData.Id;
                cardmapping.UserInventoryId = userInventory.Id;
                cardmapping.Count = 1;
                await _DataAccess.CardDataAccess.UpsertCardMappingAsync(cardmapping);
            }
            return RedirectToAction("Details", model);
        }
        [HttpPost]
        public async Task<IActionResult> AddToDeck(SearchDetailsViewModel model)
        {
            
            int deckId;
            if (int.TryParse(model.DeckId, out deckId))
            {
                var card = await _DataAccess.CardDataAccess.GetCardByNameAsync(model.Name);
                if (card == null)
                {
                    var apiCard = await _YGOProDeckAccess.GetCardByNameAsync(model.Name);
                    if (apiCard.CardImages != null && apiCard.CardImages.Count > 0)
                    {
                        apiCard.ImageBytes = _YGOProDeckAccess.GetCardImage(apiCard.CardImages.First());
                    }
                    card = await _DataAccess.CardDataAccess.Upsert(apiCard);
                }
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
                if (string.IsNullOrWhiteSpace(userId))
                {
                    return RedirectToAction("Details", model);
                }
                var userInventory = await _DataAccess.UserInventoryDataAccess.GetUserInventoryByUserAsync(userId);
                var userCardMapping = _DataAccess.CardDataAccess.GetSpecificCardMappingForUserAsync(userInventory.Id, card.Id);
                if (userCardMapping == null)
                {
                    var cardmapping = new InventoryCardMapping();
                    cardmapping.CardId = card.Id;
                    cardmapping.UserInventoryId = userInventory.Id;
                    cardmapping.Count = 1;
                    await _DataAccess.CardDataAccess.UpsertCardMappingAsync(cardmapping);
                }
                var mapping = await _DataAccess.DeckDataAccess.GetDeckCardMappingAsync(deckId, card.Id);
                if (mapping != null)
                {
                    mapping.Count++;
                    await _DataAccess.DeckDataAccess.UpsertDeckCardMappingAsync(mapping);
                }
                else
                {
                    mapping = new DeckCardMapping();
                    mapping.CardId = card.Id;
                    mapping.DeckId = deckId;
                    mapping.Count = 1;
                    await _DataAccess.DeckDataAccess.UpsertDeckCardMappingAsync(mapping);

                }
            }
            return RedirectToAction("Details", model);
        }
    }
}

FinalProject/Views/Shared/AddCardModal.cshtml
@{
    ViewBag.Title = "Add Card To Deck";
}

<title>@ViewBag.Title</title>

<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">

<style>
    .button {
        background-color: #4CAF50; /* Green */
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }

    .button1 {
        border-radius: 2px;
    }

    .button2 {
        border-radius: 4px;
    }

    .button3 {
        border-radius: 8px;
    }

    .button4 {
        border-radius: 12px;
    }

    .button5 {
        border-radius: 50%;
    }
</style>
<div>
    <h2 style="background-color: Yellow;color: Blue; text-align: center; font-style: oblique">Satyaprakash Bootstrap PopUp</h2>
    <fieldset>
        <legend style="color:orangered">Click On Satyaprakash Bootstrap PopUp</legend>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">

                    <button id="btnShowModal" type="button"
                            class="btn btn-sm btn-default pull-left col-lg-11 button button4">
                        Satya Modals
                    </button>

                    <div class="modal fade" tabindex="-1" id="loginModal"
                         data-keyboard="false" data-backdrop="static">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">
                                        ×
                                    </button>
                                    <h4 class="modal-title">Satya Login</h4>
                                </div>
                                <div class="modal-body">
                                    <form>
                                        <div class="form-group">
                                            <input class="form-control" type="text"
                                                   placeholder="Login Username" id="inputUserName" />
                                        </div>
                                        <div class="form-group">
                                            <input class="form-control" placeholder="Login Password"
                                                   type="password" id="inputPassword" />
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary button button4">Sign</button>
                                    <button type="button" id="btnHideModal" class="btn btn-primary button button4">
                                        Hide
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </fieldset>
</div>
<footer>
    <p style="background-color: Yellow; font-weight: bold; color:blue; text-align: center; font-style: oblique">
        ©
        <script>document.write(new Date().toDateString());</script>
    </p>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">

</script>
<script src="bootstrap/js/bootstrap.min.js"></script>

<script type="text/javascript">

        $(document).ready(function () {
            $("#btnShowModal").click(function () {
                $("#loginModal").modal('show');
            });

            $("#btnHideModal").click(function () {
                $("#loginModal").modal('hide');
            });
        });
</script> 

FinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TradeListings" asp-action="Browse">Trade Listings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>